apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ambassador
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ambassador
  source:
    repoURL: https://github.com/milsman2/ambassador
    targetRevision: HEAD
