apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: kong
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: kong
  source:
    repoURL: https://github.com/milsman2/kong
    targetRevision: HEAD
