apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 # - cert-manager.yaml
  - metallb.yaml
 # - longhorn.yaml
  #- ingress-nginx.yaml
  - linkerd2-cni.yaml
  - linkerd.yaml
  - linkerd-viz.yaml
