apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: linkerd-viz
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: linkerd-viz
  project: default
  source:
    repoURL: https://github.com/milsman2/linkerd-viz
    targetRevision: HEAD
