apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: linkerd2-cni
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: linkerd-cni
  project: default
  source:
    repoURL: https://github.com/milsman2/linkerd2
    targetRevision: HEAD
