apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

nameSuffix: -x86

patches:
  - path: patch.yaml
    target:
      kind: Application
  - path: kubernetes-ingress-nginx-patch.yaml
    target:
      kind: Application
      name: kubernetes-ingress-nginx
  - path: cert-manager-patch.yaml
    target:
      kind: Application
      name: cert-manager-x86
  - path: metallb-patch.yaml
    target:
      kind: Application
      name: metallb
  - path: nginx-patch.yaml
    target:
      kind: Application
      name: nginx
