apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../umbrella-apps

nameSuffix: -x86

patches:
  - path: patch.yaml
    target:
      kind: Application
  - path: mysql-patch.yaml
    target:
      kind: Application
      name: mysql
  - path: cert-manager-patch.yaml
    target:
      kind: Application
      name: cert-manager
  - path: metallb-patch.yaml
    target:
      kind: Application
      name: metallb
  - path: longhorn-patch.yaml
    target:
      kind: Application
      name: longhorn
  - path: ingress-nginx-patch.yaml
    target:
      kind: Application
      name: ingress-nginx-patch
