apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: cert-manager-issuers
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
  project: default
  source:
    path: cert-manager-amd64
    repoURL: https://github.com/milsman2/amd64-apps
    targetRevision: HEAD
