apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: linkerd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: linkerd
  project: default
  source:
    path: linkerd-amd64-production/linkerd2
    repoURL: https://github.com/milsman2/linkerd2
    targetRevision: HEAD
