apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: tpctk-db
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: the-precast-toolkit
  project: default
  source:
    path: tpctk-db
    repoURL: https://github.com/milsman2/the-precast-toolkit
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
