apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: tpl-kubegres.yaml
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: alpaca
  project: default
  source:
    path: kubegres
    repoURL: https://github.com/milsman2/the_punters_league
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
