apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: cert-manager
  source:
    path: cert-manager
    repoURL: https://github.com/milsman2/amd64-apps
    targetRevision: HEAD
  #syncPolicy:
   # automated:
    #  prune: true
     # selfHeal: true
