apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: homeassistant
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: home-assistant
  source:
    repoURL: https://github.com/milsman2/kustomize-home-assistant
    targetRevision: HEAD
