apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ingress-nginx
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ingress-nginx
  source:
    repoURL: https://github.com/milsman2/ingress-nginx
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
