apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
  project: default
  source:
    path: kustomize-kubernetes-ingress-nginx
    repoURL: https://github.com/milsman2/argo-experiments
    targetRevision: HEAD
