apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: kubernetes-ingress-nginx
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn-system
  project: default
  source:
    repoURL: https://github.com/milsman2/kustomize-longhorn
    targetRevision: HEAD
