apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: cert-manager-rpi
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://192.168.30.69:6443
  project: default
  source:
    path: cert-manager-rpi-production
    repoURL: https://github.com/milsman2/kustomize-cert-manager-rpi
    targetRevision: HEAD
