apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - kubernetes-ingress-nginx.yaml
  - metallb.yaml
  - nginx.yaml
  - quake.yaml
  - cert-manager-arm64.yaml
  - kubernetes-ingress-nginx-arm64.yaml
  - metallb-arm64.yaml
  - nginx-arm64.yaml
