apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

nameSuffix: -rpi

patches:
  - path: patch.yaml
    target:
      kind: Application
  - path: kubernetes-ingress-nginx-patch.yaml
    target:
      kind: Application
      name: kubernetes-ingress-nginx-patch
