apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../umbrella-apps
- ../../pi-apps

nameSuffix: -rpi

patches:
  - path: patch.yaml
    target:
      kind: Application
  - path: kubernetes-ingress-nginx-patch.yaml
    target:
      kind: Application
      name: kubernetes-ingress-nginx
  - path: cert-manager-patch.yaml
    target:
      kind: Application
      name: cert-manager
  - path: metallb-patch.yaml
    target:
      kind: Application
      name: metallb
  - path: nginx-patch.yaml
    target:
      kind: Application
      name: nginx
  - path: longhorn-patch.yaml
    target:
      kind: Application
      name: longhorn
  - path: kuma-patch.yaml
    target:
      kind: Application
      name: uptime-kuma
  - path: home-assistant-patch.yaml
    target:
      kind: Application
      name: home-assistant
 # - path: esphome-patch.yaml
 #   target:
 #     kind: Application
 #     name: esphome
