apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesStrategicMerge:
- cert-manager-patch.yaml
- kubernetes-ingress-nginx-patch.yaml
- metallb-patch.yaml
- nginx-patch.yaml