apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ghost
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: mysql
  source:
    repoURL: https://github.com/milsman2/rpi-applications
    targetRevision: HEAD
