apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: home-assistant
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: home-assistant
  source:
    repoURL: https://github.com/milsman2/home-assistant
    targetRevision: HEAD
