apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

patchesStrategicMerge:
- |- 
  apiVersion: apps/v1
  kind: Application
  metadata:
    name: cert-manager
  spec:
    destination:
      server: https://kubernetes.default.svc
