apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: alpaca
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: alpaca
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/milsman2/kanebulnes
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
