apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: eth-exporter
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: eth-exporter
  project: default
  source:
    path: eth-exporter
    repoURL: https://github.com/milsman2/eth_tracker
    targetRevision: HEAD
