apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: eth_kube_exporter
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: alpaca
  project: default
  source:
    path: eth_exporter_kube
    repoURL: https://github.com/milsman2/eth_tracker
    targetRevision: HEAD
