apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: jupyterlab
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jupyterlab
  project: default
  source:
    path: jupyterlab/z2jh
    repoURL: https://github.com/milsman2/amd64-apps
    targetRevision: HEAD
#  syncPolicy:
 #   automated:
  #    selfHeal: true
   #   prune: true
