apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
   - argocd-ingress.yaml
   - cert-manager.yaml
   - cert-manager-issuers.yaml
   - eth-exporter.yaml
   - fsi-postgresql.yaml
   - fsi-pgadmin4.yaml
   - ghost.yaml
   - ingress-nginx.yaml
   - inlets-pro-client.yaml
#  - kanecraft.yaml
   - kubegres.yaml
   - librespeed.yaml
   - longhorn.yaml
   - longhorn-backup.yaml
   - metallb.yaml
#  - minecraft.yaml
   - mosquitto.yaml
   - timescaledb.yaml
   - nginx.yaml
   - openfaas.yaml
   - prometheus.yaml
   - quake-kube.yaml
   - react-kube-demo.yaml
   - run-pop-kube-frontend.yaml
   - run-pop-pgadmin4.yaml
 # - sealed-secrets.yaml
   - the-precast-toolkit.yaml
   - tpctk-fs-code.yaml
   - tpctk-fs-pgadmin4.yaml
   - tpctk-fs-kube-backend.yaml
   - tpctk-fs-kube-frontend.yaml
   - tpctk-fs-kubegres.yaml
   - tpctk-fs-mysql.yaml
   - tpctk-fs-umami.yaml
   - tpl-kubernetes.yaml
   - tpl-pgadmin4.yaml
   - tpl-timescaledb.yaml
   - uptime-kuma.yaml

patches:
  - path: patch.yaml
    target:
      kind: Application
