apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
   - alpaca-code-server.yaml
   - alpaca-kubegres.yaml
   - alpaca-pgadmin4.yaml
   - argocd-ingress.yaml
   - alpaca.yaml
   - carlos-code-server.yaml
   - cert-manager.yaml
   - cert-manager-issuers.yaml
   - fsi-postgresql.yaml
   - fsi-pgadmin4.yaml
   - ghost.yaml
   - ingress-nginx.yaml
   - inlets-pro-client.yaml
#  - kanecraft.yaml
   - kubegres.yaml
   - librespeed.yaml
 # - linkerd.yaml
 # - linkerd-viz.yaml
 # - linkerd-ingress.yaml
 # - linkerd-jaeger.yaml
   - longhorn.yaml
   - longhorn-backup.yaml
   - metallb.yaml
   - miles-code-server.yaml
#  - minecraft.yaml
   - nginx.yaml
   - openfaas.yaml
   - quake-kube.yaml
   - react-kube-demo.yaml
 # - sealed-secrets.yaml
   - the-precast-toolkit.yaml
   - tpctk-code-server.yaml
   - tpctk-fs-pgadmin4.yaml
   - tpctk-fs-kube-backend.yaml
   - tpctk-fs-kube-frontend.yaml
   - tpctk-fs-kubegres.yaml
   - tpctk-fs-mysql.yaml
   - tpctk-fs-umami.yaml
   - tpl-pgadmin4.yaml
   - tpl-frontend.yaml
   - tpl-kubegres.yaml
   - uptime-kuma.yaml
   - vaultwarden.yaml

patches:
  - path: patch.yaml
    target:
      kind: Application
