apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: linkerd-ingress
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: linkerd-viz
  project: default
  source:
    path: linkerd2/linkerd-ingress
    repoURL: https://github.com/milsman2/amd64-apps
    targetRevision: HEAD
