apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: promscale
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: promscale
  project: default
  source:
    path: promscale
    repoURL: https://github.com/milsman2/amd64-apps
    targetRevision: HEAD
