apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: run-pop-pgadmin4
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: run-pop
  project: default
  source:
    path: run_pop_pgadmin4
    repoURL: https://github.com/milsman2/run_pop
    targetRevision: HEAD
