apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: sealed-secrets
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
  project: default
  source:
    path: sealed-secrets
    repoURL: https://github.com/milsman2/amd64-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
