apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: tpctk-fs-kube-frontend
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: the-precast-toolkit-fs
  project: default
  source:
    path: tpctk-fs-kube-frontend
    repoURL: https://github.com/milsman2/the-precast-toolkit-fs
    targetRevision: HEAD
