apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: tpl-rabbitmq
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: the-punters-league
  project: default
  source:
    path: tpl-rabbitmq
    repoURL: https://github.com/milsman2/the_punters_league
    targetRevision: HEAD
